### ISSUE TITLE
Something to add to the OS Imaging page...

### ISSUE THREAD

**Issue by frankincell** [dannen/kudo3dbean#1]
In case anyone needs it...   Here’s an image of my sd-card.
https://drive.google.com/open?id=1dS2DkVGlHA9xqL9CaeGpc3h1F6701CHO 2
It’s approximately 1,749 MB in size, so it may take a bit to download.
Inside the .zip file is an 8GB .img file.
You can write the image to your sdcard with https://rufus.ie/en_IE.html or the disk imaging program of your choice.

**Comment by dannen** [comment]
thanks! I just noticed your post in the kudo forums with the exact same link.  I'll add a reference to your data in the os Imaging page.
